# Generated by Django 4.2.5 on 2023-10-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesstoremodel',
            name='dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('IPE', 'IPE'), ('CE', 'CE'), ('ICT', 'ICT')], max_length=30),
        ),
    ]
