# Generated by Django 4.2.5 on 2023-10-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
