# Generated by Django 4.2.5 on 2023-10-04 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0005_alter_coursesstoremodel_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='profile_id',
            field=models.ForeignKey(default='rifat', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursesstoremodel',
            name='course_name',
            field=models.CharField(default='Enter your name', max_length=30),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
