# Generated by Django 4.2.5 on 2023-10-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_profilemodel_profile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='profile_id',
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
