# Generated by Django 4.2.5 on 2023-10-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_profilemodel_profile_id_alter_profilemodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='cover_picture',
            field=models.ImageField(default=False, upload_to='img/cover_pic'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
