# Generated by Django 4.2.5 on 2023-10-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_profilemodel_cover_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='cover_picture',
            field=models.ImageField(default=False, upload_to='img/cover_pic'),
        ),
    ]
