# Generated by Django 4.2.5 on 2023-10-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_profilemodel_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesstoremodel',
            name='course_description',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='coursesstoremodel',
            name='course_img',
            field=models.ImageField(default=False, upload_to='img/courses'),
        ),
        migrations.AlterField(
            model_name='coursesstoremodel',
            name='course_name',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='coursesstoremodel',
            name='course_video',
            field=models.FileField(default=False, upload_to='files/courses'),
        ),
    ]
